### ISSUE TITLE
RadGrid equivalent for NodeJS

### ISSUE THREAD

**Issue by alana1** [bchavez/RethinkDb.Driver#100]
Hello,

Do you know if there is an equivalent API for use similar to RadGrid in Nodejs?

**Comment by bchavez** [comment]
https://github.com/bchavez/RethinkDb.Driver/wiki/ReGrid-File-Storage

I was [co-author on the ReGrid spec](https://github.com/internalfx/regrid-spec). Of course the C# driver would have a ReGrid API! :smiley_cat: 

:art: :dash: [**Marshmello - CoLoUR**](https://www.youtube.com/watch?v=6UhNJC8OyVA)

**Comment by oliverjanik** [comment]
RadGrid sounds much better than ReGrid :-D
