### ISSUE TITLE
How to connect C# winform (use devexpress) to RethinkDB?

### ISSUE THREAD

**Issue by hitechqb** [bchavez/RethinkDb.Driver#106]
Can you help me make 1 small project Realtime use C# winform connect RethinkDB with actions as: add, edit, remove, save... ?

Thank you so much!

**Comment by bchavez** [comment]
Hello,

Unfortunately, I can't help you build an application using WinForms; however, you may find this particular GitHub discussion and WinForms demo helpful: https://github.com/bchavez/RethinkDb.Driver/issues/105.

Furthermore, you might need to dive deeper into documentation topics regarding [**this C# driver**](https://github.com/bchavez/RethinkDb.Driver/wiki), [**the ReQL/RethinkDB language**](https://rethinkdb.com/api/java/), **WinForms data binding**, and **DevExpress WinForm controls**.

I'd like to encourage you to sign-up for Slack (http://rethinkdb.slack.com). Slack is a chatroom where you can find free help with other RethinkDB users. There is another user (Nam Ly) on Slack **lynam:** who is also using WinForms and this C# RethinkDB driver. He might be able to help you.

Also, just a quick reminder, submitting GitHub issues in this repository are normally reserved for changes to the driver source code, to request new features, and to report bugs for this driver. So, regarding help related questions, Slack would be your best avenue to inquire for help.

Thanks,
Brian

:boom: :fire: [***"Set it ablaze like a candle wick... Light it up, light it up..."***](https://www.youtube.com/watch?v=qDcFryDXQ7U)

**Comment by hitechqb** [comment]
Thanks,
Nam Ly is my friend 🗡
