### ISSUE TITLE
Regrid: support client generated IDs for FileInfo

### ISSUE THREAD

**Issue by oliverjanik** [bchavez/RethinkDb.Driver#113]
Perhaps in UploadOptions which is exposed by Bucket.OpenUploadStream?

**Comment by bchavez** [comment]
Hi Oliver,

Could you provide a more concrete / use-case example of what you're trying to do?

Thanks,
Brian

:dash: :walking: ***["Bubbles of gas in my brain... Send me off balance, it's not enough"](https://www.youtube.com/watch?v=AS6NfeREKPk)***

**Comment by oliverjanik** [comment]
Sure,

We have an app that provides file upload functionality and it supports that even when you're offline. Then it let's you upload the files when you come back online later.

Now this means we have to identify and generate IDs for files on the client in any case. We use GUIDs for that.

Now if we could get ReGrid to accept an ID that's pre-generated that would save us some complicated transformations. RethinkDB supports this usecase quite well for normal documents.

Think of it as allowing "distributed" File storage and I'm just trying to sync it up to ReGrid ;-)

**Comment by bchavez** [comment]
Hi Oliver,

Seems legit. [I was glossing over the download APIs for ReGrid](https://github.com/bchavez/RethinkDb.Driver/blob/ef07560225e9aa2d363e67830430e83ac2a60a39/Source/RethinkDb.Driver.ReGrid/Bucket.Download.cs#L58) and looks like we allow the ability to retrieve files by `fileId`.

So, it does seem natural to allow setting the `Id` for a `FileInfo` in the name of API symmetry and overall feel.

In the case of a failed upload / (and retry), I think we'll `throw` an exception if you try creating a file with the same `FileInfo.Id` twice. I haven't checked, but IIRC some bad things would happen if we tried to allow resuming a failed upload. Hope that seems reasonable to you.

I'll send a PR in a few minutes.

:beach_umbrella: :trumpet: **[Beach Boys - Good Vibrations (Nick Warren bootleg)](https://www.youtube.com/watch?v=PZiV-Sd2uOs)**

**Comment by oliverjanik** [comment]
Thanks for the quick response! Error on conflict is reasonable behaviour IMO.

**Comment by bchavez** [comment]
No problem. :+1:

[ReGrid `v2.3.19`](https://www.nuget.org/packages/RethinkDb.Driver.ReGrid/2.3.19) now available. `UploadOptions.ForceFileId` should do it. =)

:walking: :sunglasses: ***["So don't delay... act now supplies are running out..."](https://www.youtube.com/watch?v=LQj--Kjn0z8)***
