### ISSUE TITLE
Update several documents in one transaction

### ISSUE THREAD

**Issue by iSotelo** [bchavez/RethinkDb.Driver#117]
Hello.

How I can update several documents in one transaction using update(). 
I Need update one list to 3000 records (previously mapped in MyClassMapper) only using update o replace() in one transacction.

Example: 

/// My classs mapper is my model
`List<MyClassMapper> recordsUpdate = new List<MyClassMapper>();`

/// TODO: Fill my list recordsUpdate using foreach or while

/// Vars: DBLocal, Table, Connection is ready and instance
`R.Db(DBLocal).Table(table).Update(recordsUpdate).Run(Connection); `

My problem is that not change the records, but if i using update() method in one record or one for one then yes update record, but this take a lot of time. 

Thanks

**Comment by bchavez** [comment]
Hi @iSotelo , I'd be happy to answer your question in the Slack channel. You can tag me @bchavez in Slack.

Respectfully, it's very important to avoid using [GitHub issues](https://github.com/bchavez/RethinkDb.Driver/blob/master/.github/ISSUE_TEMPLATE.md) for help requests.

Many thanks,
Brian

:walking_woman: :walking_man: **[Missing Persons - Walking in L.A.](https://www.youtube.com/watch?v=R_UpLtGEWoY)**
