### ISSUE TITLE
Is it possible to use this driver with Unity3D?

### ISSUE THREAD

**Issue by eclipse1985** [bchavez/RethinkDb.Driver#118]
As the subject, it is possible to use this driver with Unity3D?

**Comment by bchavez** [comment]
Responded to your question on Slack:
> With older versions of Unity, no I don't think it's possible. IIRC, I heard Unity is developing a new version (vaguely recall v5 I think) that supports the latest features of .NET4.5/.NETCore and C#. You'll probably have a better chance at getting the C# driver to run on the newer/beta version of Unity. You'll have to try it and see if it works. I suspect there still might be some issues with Unity since the C# driver does have hard dependencies on Thread, Socket, and Encryption APIs that might not be fully available in Unity. If there's anything we can do to remedy Unity issues without having a large impact on the driver's maintainability let me know and we can explore it more.

> Also, I'd like to briefly mention the best place to ask questions is here in Slack. I'd like to keep GitHub issues reserved for issues that are directly related to the driver source-code like confirmed bugs reports and feature requests

:sunglasses: 

:beach_umbrella: :trumpet: **[Beach Boys - Good Vibrations (Nick Warren bootleg)](https://www.youtube.com/watch?v=PZiV-Sd2uOs)**
