### ISSUE TITLE
How can i use the durability and noReply params in insert query ?

### ISSUE THREAD

**Issue by karev** [bchavez/RethinkDb.Driver#119]
hello,
i searched the documentation but i cant find where i can pass the durability: 'soft'
 and the noreply paramaters to the insert query.

any hint will be appreciated.

**Comment by bchavez** [comment]
Hello @karev,

I appreciate your question; however, submitting a GitHub issue is not truly the appropriate place to ask for help. As mentioned [in the issue template here](https://github.com/bchavez/RethinkDb.Driver/blob/master/.github/ISSUE_TEMPLATE.md), submitting GitHub issues are reserved for confirmed bugs, feature requests, and changes to the source code.

The more appropriate place to ask for help is outlined here:
https://github.com/bchavez/RethinkDb.Driver#getting-help

Respectfully,
Brian

:beach_umbrella: :trumpet: **[Beach Boys - Good Vibrations (Nick Warren bootleg)](https://www.youtube.com/watch?v=PZiV-Sd2uOs)**
