### ISSUE TITLE
Logging using vNext/AspNet5/DNX/etc

### ISSUE THREAD

**Issue by fiLLLip** [bchavez/RethinkDb.Driver#12]
In my new projects using vNext/AspNet5/DNX or whatever they are calling it today, I do not have the App.config or Web.config as described in the [wiki](https://github.com/bchavez/RethinkDb.Driver/wiki/Protocol-Debugging).
How do I activate logging here? Could it be possible to enable this in-code?

**Comment by bchavez** [comment]
Hi @fiLLLip ,

Here's a sample app for the Logging extension in DNX:

https://github.com/aspnet/Logging/tree/dev/samples/SampleApp

Roughly looks like:
```
// a DI based application would get ILoggerFactory injected instead
var factory = new LoggerFactory();

// getting the logger immediately using the class's name is conventional
_logger = factory.CreateLogger<Program>();

// providers may be added to an ILoggerFactory at any time, existing ILoggers are updated
factory.AddNLog(new global::NLog.LogFactory());

//Then log something
_logger.LogInformation("Starting");
```

Let me know if this helps or if you run into any trouble.

**Comment by fiLLLip** [comment]
I have logging in my app now with Serilog linked to the logging extension, but the RethinkDb.Driver is not logging to it now. What I would like is logging of what the driver is doing, and why it's failing. All I got now is the exceptions, and I would like to give you more information when I encounter errors than the exception name and message.

**Comment by bchavez** [comment]
is the log level setting set to trace?

**Comment by fiLLLip** [comment]
I've set the log level to Debug in my Api project, which pulls in my DataAccess project that handles the RethinkDb connection. Do I have to set up logging inside the DataAccess project as well?

**Comment by bchavez** [comment]
Hi @fiLLLip , I'm not sure. It's sort of out of my area of expertise at the moment. I'm not super familiar with DNX yet since it's still in Beta (RC soon). I'll have to setup a example project to explore the issue more.

**Comment by bchavez** [comment]
Hi @fiLLLip , I had some time to look at this. Use the RethinkDb.Driver `EnableRethinkDbLogging();` extension method for DNX/CoreCLR in your `Startup.cs` or console start up. It's an extension for `ILoggerFactory loggerFactory`.

Here's the logging configuration I used:
```
loggerFactory.MinimumLevel = LogLevel.Debug;
loggerFactory.AddConsole(LogLevel.Debug);
loggerFactory.AddDebug(LogLevel.Debug);
loggerFactory.EnableRethinkDbLogging();
```

**Comment by fiLLLip** [comment]
I'm using both `dnx451` and `dnxcore50` like the templates in ASP.NET are using, and that gives me the following error:
![image](https://cloud.githubusercontent.com/assets/1264369/11239691/d1c98d38-8ded-11e5-81b2-2a19cfd2de1c.png)
Is it possible to make the extension work with both runtimes?

**Comment by bchavez** [comment]
Hi @fiLLLip , I rejigged the DNX dependencies, **7 alpha4** should have this fixed against RC1 (released just today). **7 alpha 4** should work in `dnx451` and `dnxcore50`. Ugh, all these target frameworks without any documentation is painful. Hopefully, Microsoft with all this new DNX Core stuff will get documented now that RC1 is released.

Also, I moved our dependency run-time to CoreCLR RC1. So, when when trying **7 alpha 4**, please make sure your project is upgraded to RC1. Here's more about today's CoreCLR RC1 announcement:

http://blogs.msdn.com/b/dotnet/archive/2015/11/18/announcing-net-core-and-asp-net-5-rc.aspx

http://blogs.msdn.com/b/webdev/archive/2015/11/18/announcing-asp-net-5-release-candidate-1.aspx
