### ISSUE TITLE
Can not connect to RethinkDB localhost database.

### ISSUE THREAD

**Issue by sanzor** [bchavez/RethinkDb.Driver#127]
I am trying to simply establish a connection with the rethink db.
I set up a server on port 9300.The localhost rethinkdb interface works.However when i try to connect to the database using this simple command  it wont get past the connect.It will wait forever and never connect nor display an error message.Am i missing anything?

```
RethinkDB r = new RethinkDB();
Connection con=await r.Connection().Hostname("localhost").Port(9300).ConnectAsync();
DbCreate rt=r.DbCreate("testdb");
```

**Comment by bchavez** [comment]
Hey @sanzor,

Thank you for your question. I hope I don't sound rude, but the best place to get basic help is from RethinkDB's slack channel here: https://github.com/bchavez/RethinkDb.Driver#getting-help

GitHub issues in this repository, [as outlined in our issue template](https://github.com/bchavez/RethinkDb.Driver/blob/master/.github/ISSUE_TEMPLATE.md), are mostly reserved for bugs, feature requests, and issues related directly to the source code in the repository. Not so much for help related requests.

But to answer your question, RethinkDB opens 3 ports, 1) for the UI admin, 2) for cluster communication, and 3) for driver clients. You want to make sure that you're connecting the C# driver to the proper driver client port. Also, you'll want to double check your firewall rules.

If you have any other question, please feel free to start a discussion on the slack channel. You can tag me @bchavez in Slack and I'll try to help you when I have some free time.

Thanks, I appreciate it.
Brian

:beach_umbrella: :trumpet: **[Beach Boys - Good Vibrations (Nick Warren bootleg)](https://www.youtube.com/watch?v=PZiV-Sd2uOs)**

**Comment by sanzor** [comment]
Hello,Thank you for your timely response.I did read the rules and knew about the slack channel.Unfortunately i didnt get the invite in the group.I have waited for a mail invite(both inbox and spam) bit none came.So i posted here.I am sorry for breaking the aforementioned rules.
Adrian

Sent from Yahoo Mail on Android 
 
  On Thu, Apr 12, 2018 at 11:26 PM, Brian Chavez<notifications@github.com> wrote:   
Hey @sanzor,

Thank you for your question. I hope I don't sound rude, but the best place to get basic help is from RethinkDB's slack channel here: https://github.com/bchavez/RethinkDb.Driver#getting-help

GitHub issues in this repository, as outlined in our issue template, are mostly reserved for bugs, feature requests, and issues related directly to the source code in the repository. Not so much for help related requests.

But to answer your question, RethinkDB opens 3 ports, 1) for the UI admin, 2) for cluster communication, and 3) for driver clients. You want to make sure that you're connecting the C# driver to the proper driver client port. Also, you'll want to double check your firewall rules.

If you have any other question, please feel free to start a discussion on the slack channel. You can tag me @bchavez in Slack and I'll try to help you when I have some free time.

Thanks, I appreciate it.
Brian

 🏖 🎺 Beach Boys - Good Vibrations (Nick Warren bootleg)

**Comment by sanzor** [comment]
Well i had my UI set at port 9300 with the -http-port command.I must admit that i used this same for for connecting with the driver via C#.So if the ports are different i just set the connection.builder with the desired port? Or it is already allocated and i have to find which port is used?

Sent from Yahoo Mail on Android 
 
  On Fri, Apr 13, 2018 at 12:01 AM, Brian Chavez<notifications@github.com> wrote:   
Hey Adrian,

Ah, okay. No problem. Yea, it does seems like they've been having issues lately: rethinkdb/rethinkdb#6626

So, were you able to resolve your connection issue? If the problem persists, have you tried using the --bind all command line argument?

**Comment by sanzor** [comment]
Do i have to find the client driver port or i set it with the Port() method?

Sent from Yahoo Mail on Android 
 
  On Fri, Apr 13, 2018 at 12:05 AM, bercovici adrian<adriansan_93@yahoo.com> wrote:   Well i had my UI set at port 9300 with the -http-port command.I must admit that i used this same for for connecting with the driver via C#.So if the ports are different i just set the connection.builder with the desired port? Or it is already allocated and i have to find which port is used?

Sent from Yahoo Mail on Android 
 
  On Fri, Apr 13, 2018 at 12:01 AM, Brian Chavez<notifications@github.com> wrote:   
Hey Adrian,

Ah, okay. No problem. Yea, it does seems like they've been having issues lately: rethinkdb/rethinkdb#6626

So, were you able to resolve your connection issue? If the problem persists, have you tried using the --bind all command line argument?

**Comment by bchavez** [comment]
Correct. You should not be connecting the C# driver to the HTTP UI port (`--http-port`).

The correct port number the C# driver should be connecting to is the one specified by `--driver-port` argument. By default, IIRC is `28015`. The C# driver will automatically use `28015` by default without having to call `.Port()` method.

Let me know if that helps!

Brian

:collision: :dizzy: ***["Crashing, hit a wall. Right now I need a miracle..."](https://www.youtube.com/watch?v=s8XIgR5OGJc)***

**Comment by bchavez** [comment]
Hi Adrian,

I tried to see what was going on with slack signups few days ago and didn't get much of a response. I think, right now, your best bet is voice your concern and make your request known here: https://github.com/rethinkdb/rethinkdb/issues/6626

I tired looking for some kind of invite link, but couldn't find one.
