### ISSUE TITLE
Change license back to Apache

### ISSUE THREAD

**Issue by oliverjanik** [bchavez/RethinkDb.Driver#131]
I just noticed a change you made to license in April last year. I really think this hurts adoption. It's a bit of a bait & switch if you ask me.

While it's not an issue for me yet, it might cause me headaches in the future. 

Please reconsider a switch back to standard Apache License.

**Comment by bchavez** [comment]
Hey Oliver,

I appreciate your concern. TBH, it's hard to say if the dual licensing really hurts adoption. I would say there is definitely another side to the story.

I was approached by a few people asking for new SSL features. These people would not have used this driver without SSL. They were willing to pay a small commercial license to 1) have SSL implemented and 2) use SSL features. Moreover, a commercial license gave them some assurance that the driver they were about to build their app on wasn't going to turn into a pile of unmaintained abandonware (like other unnamed driver projects).

It shouldn't feel like a bait and switch. Assuming you're using the NuGet package, I didn't remove any of your rights to continue using the driver as you were before the license change. I only ***added value*** to the driver by adding SSL features and licensed the API that enables SSL features inside the driver.

The cold, hard, dirty truth about open source is that _it's hard_. It's hard to maintain a high-quality open source project without some kind of economic model to support that effort. Take a quick survey of the landscape: RehtinkDB as a company shut down. The official drivers for RethinkDB are showing their age with unresolved issues piling up. There is hardly any human effort to maintain "official" drivers. Last **Java** driver release: **Jan 2016**.

Now, contrast this to the C# driver: IMHO, C# driver continues to be one of the best supported, well maintained, and fastest bugfix-to-release cycle drivers currently available for RethinkDB. Last **C#** driver release: **4 days ago**.

Prior to the license change, after RethinkDB shut down, there were times when I felt like abandoning this project, but after the license change, the economics has kept me in the game.

For now, I feel keeping the dual license is the best approach moving forward to ensure our community continues receiving high-quality driver releases and fast response times.

Thanks,
Brian

:ear_of_rice: :stew: ***["Out here in the fields... I fight for my meals... It's only teenage wasteland..."](https://www.youtube.com/watch?v=IXWNSb4nUDY)***
