### ISSUE TITLE
Resolution function on OptArg insert conflict

### ISSUE THREAD

**Issue by rgarciacejudo** [bchavez/RethinkDb.Driver#142]
Hi!

How do you use OptArg function in order to implement a resolution function on insert conflict?

I think something similar to Java API:

// assume newMemos is a list of memo documents to insert
r.table("memos").insert(new_memos).optArg("conflict",
    (id, old_doc, new_doc) -> new_doc.merge(
        r.hashMap(content, old_doc.g("content").add("\n")
                  .add(new_doc.g("content")))
    )
).run(conn);

**Comment by bchavez** [comment]
Hey there,

If you need help using the driver, please have a look here: https://github.com/bchavez/RethinkDb.Driver#getting-help

and join and ask your question in Discord Server 1. GitHub issues here are reserved for changes to the source code.

Thanks,
Brian
