### ISSUE TITLE
Add Error codes to Exceptions

### ISSUE THREAD

**Issue by oliverjanik** [bchavez/RethinkDb.Driver#145]
If I'm not mistaken I can't tell the difference between

```
RethinkDb.Driver.ReqlOpFailedError
Cannot perform read: primary replica for shard ["", +inf) not available
```

and

```
RethinkDb.Driver.ReqlOpFailedError
Table `example.order_form_data` does not exist.
```

correct? 

I'm looking into availability and it's worth retrying on the first error but not on the second one.

If exceptions had error codes or some other way of telling them apart (message text notwithstanding) that would enable me to write more granular retry policies.

**Comment by bchavez** [comment]
Exceptions like `ReqlOpFailedError` are built into the protocol. If the protocol doesn't provide an error code, the driver can't provide one either.

https://github.com/bchavez/RethinkDb.Driver/blob/044749812e51b918c09724cbe54a7d99e281cfc1/Source/RethinkDb.Driver/ErrorBuilder.cs#L39-L87

https://github.com/bchavez/RethinkDb.Driver/blob/044749812e51b918c09724cbe54a7d99e281cfc1/Source/RethinkDb.Driver/Generated/Proto/ResponseType.cs#L11-L20

Try turning on protocol debugging, trace both exceptions over the wire, and see if you can detect anything different besides the error `msg` string in both JSON responses.

If you can detect some other discriminator value (like an error code), re-open the issue and let me know and I'll take a look at adding it. IIRC, it is not possible with the current protocol implementation.

Hope that helps,
Brian

**Comment by oliverjanik** [comment]
Too bad, I thought that might be the case. Thanks for detailed response.
