### ISSUE TITLE
Best options: RunResult, RunAtom or RunCursor

### ISSUE THREAD

**Issue by walterX12** [bchavez/RethinkDb.Driver#151]
Hi,

I would like to ask for your help. I struggle with choosing best approach to query data. I intended to use "universal" RunCursor<T>, but I hit the issue:

`The query response cannot be converted to a Cursor<T>. The run helper works with SUCCESS_SEQUENCE or SUCCESS_PARTIAL results. The server response was SUCCESS_ATOM. If the server response can be handled by this run method check T. Otherwise, if the server response cannot be handled by this run helper use .RunAtom<T> or .RunResult<T>.'

It seems that RunAtom or RunResult cannot be used to query more documents.
My query will return 0-10000 results and I would like to use it like IEnumerable<T>.

What Driver method is the best universal approach: .RunAtom<T> or .RunResult<T> or RunCursor<T> or I missed something totally ?

Sorry for such a beginner question, but I could not find best approach non Stackoverflow not in the source codes.

Thanks

**Comment by oliverjanik** [comment]
Hi @walterX12 this is my ongoing gripe with RethinkDB. See some of the discussions in #43

**Comment by walterX12** [comment]
Hi,

thank you @oliverjanik for pointing this discussion. It helped. I will study it in more details and I will close this "question". If you have developed some wrapper it might be useful to share your code.

Regards

**Comment by bchavez** [comment]
Hi @walterX12,

The best way to ask for help using the driver is to read this section here: https://github.com/bchavez/RethinkDb.Driver#getting-help

The GitHub issue tracker here is usually for tracking bugs and changes to the driver source code; not so much for help issues.

Thanks,
Brian
