### ISSUE TITLE
Get list from Table that contains 'A' in the 'message' field

### ISSUE THREAD

**Issue by Rumia0291** [bchavez/RethinkDb.Driver#152]
**used translator**

TABLE rows = ``
{
"action": 2 ,
"guild": "542599372836438016" ,
"id": "4d61a153-986e-41d3-ada0-caeb1fcb59a9" ,
"message": "AB" ,
"resp": null
}{
"action": 2 ,
"guild": "542599372836438016" ,
"id": "cd307190-ff7d-40b1-910c-02e37e9bfa39" ,
"message": "CD" ,
"resp": null
}``

The official document states that the Java Driver Match method is supports contain value

[Get all users whose name contains “li.”](https://rethinkdb.com/api/java/match/)

``r.Db("database").Table("table").Filter(new { guild = "UNIQUE_ID" }).Filter(x=> x.GetField("message").Match(MESSAGE)).Run<Model>(conn);``

If the message is AB, the data is displayed correctly. However, ABC does not display data

Can anyone help me please?

**Comment by bchavez** [comment]
Hi @Rumia0291 ,

If you need help, please refer to the readme/help section here: https://github.com/bchavez/RethinkDb.Driver#getting-help

Thanks,
Brian
