### ISSUE TITLE
Implement lambda functions as a possible argument in Insert().OptArgs("conflict",...)

### ISSUE THREAD

**Issue by jptrindade** [bchavez/RethinkDb.Driver#154]
**Context**
I want to do an "upsert" that when the entry already exists, updates an argument. However, that argument is a List,  and a normal OptArg("conflict","update") replaces the old array with the new one, I want the resulting array to be the concatenation of both arrays (without duplicates).  Is there any support for lambda functions in Insert.OptArg("conflict") in C#? In the Java documentation  there is something like this but I can't seem to implement it in C#.
![image](https://user-images.githubusercontent.com/25805946/81192552-4bfc5480-8fb2-11ea-9339-373205a5bdb9.png)

**Alternatives**

I can do this in two requests, however, I want this request to be atomical and can't find any other alternatives.

**Has the feature been requested before?**

Not that I am aware of.

**If the feature request is approved, would you be willing to submit a PR?**

No

**Comment by bchavez** [comment]
[1]:https://github.com/bchavez/RethinkDb.Driver#getting-help
[2]:https://github.com/bchavez/RethinkDb.Driver/issues/new/choose

Hi @jptrindade,

Thank you for notifying me. I see your help request in Discord and will answer it there.

In the future, please try to avoid creating GitHub issues unless we can **confirm** they are ***true*** bug reports or feature requests. If you ever have issues in the future, feel free to tag me @bchavez on Discord.

Thanks,
Brian
