### ISSUE TITLE
System.Configuration.ConfigurationErrorsException: 

### ISSUE THREAD

**Issue by reza102050** [bchavez/RethinkDb.Driver#162]
System.Configuration.ConfigurationErrorsException: 'Configuration system failed to initialize'

hi , please help me about this error,   vs2019 - .net  4.5

**Comment by bchavez** [comment]
Hi @reza102050, this is not the right place to get help or support.

Please visit the readme page here on how to get help:
https://github.com/bchavez/RethinkDb.Driver#getting-help
