### ISSUE TITLE
JsonNet v8 Compat

### ISSUE THREAD

**Issue by cecilphillip** [bchavez/RethinkDb.Driver#19]
Got this error when trying to install the nuget package

```
'Newtonsoft.Json 8.0.2' is not compatible with 'RethinkDb.Driver 2.2.0 constraint: Newtonsoft.Json (≥ 7.0.0 && < 8.0.0)'
```
I should be able to downgrade my version of JsonNET since I'm just working on a demo, but any idea when 5834bc8fa50ecb128494a7fbf0d3e0db11ffceb9 will get pushed to nuget?

**Comment by bchavez** [comment]
Hi there @cecilphillip , 

Thank you for bringing up the issue. The NuGet packages have been pushed. **v2.2.1** and **v2.2.1-beta-2** (for CoreCLR) now contain Newtonsoft v8 compatibility.

https://www.nuget.org/packages/RethinkDb.Driver

The new packages should be searchable once they're indexed. Let me know if the new packages fix your issue.

Thanks,
Brian

**Comment by cecilphillip** [comment]
This works. Thanks
