### ISSUE TITLE
Connection Usage

### ISSUE THREAD

**Issue by cecilphillip** [bchavez/RethinkDb.Driver#22]
Question...

With the Connection object, what is the recommended lifetime usage. For instance, in a web application should there be a Connection per request (which is kinda what happens with Entity Framework), or should the connection be reused for the lifetime of the process?

**Comment by bchavez** [comment]
hey there thx for your question.. connections should be per process especially when connection pooling is used. a connection can be shared among multiple threads. connection and conn pools are expensive to create and should be created once when the app boots up. ill make note of this in docs when i get home. sry for bad caps on my phone :)

**Comment by cecilphillip** [comment]
No worries.  Thanks for the quick response. This validated some odd behavior I was seeing in my aspnet app
