### ISSUE TITLE
Use Async in Windows Preview Blog Post Examples

### ISSUE THREAD

**Issue by tmds** [bchavez/RethinkDb.Driver#26]
I just saw the example at: http://rethinkdb.com/blog/rethinkdb-windows-preview/.
I was a bit surprised the example did not use the Async api provided by the library.

Unless there are good reasons examples should use the async api (examples should be exemplary).
Taking this further, the non-async API could be removed completely.

**Comment by bchavez** [comment]
Hi @tmds, 

Thank you for bringing up your concerns. I wasn't involved in writing the blog post or writing the examples. I caught wind of the announcement through social media.

I noticed there were some issues with the examples also. I tried to get them corrected as fast as possible. See: https://github.com/rethinkdb/aspnet-signalr-chat/pull/1 The initial PR doesn't make the examples fully async, but it rectified issues that I thought were most important regarding usage.

Overall, I think the main purpose of the blog post was to keep the examples as simple as possible.

I've added a `ChatHubAsync` example in a 2nd PR: https://github.com/rethinkdb/aspnet-signalr-chat/pull/2

Please feel free to make continued improvements on it. It would probably be best if you worked with the RethinkDB team directly via @segphault (aka **rkpaul** on slack). I am not part of the RethinkDB team, so there isn't much I can do to help rectify your issue regarding the blog post or examples.

**Comment by tmds** [comment]
Thanks for your feedback.
What's your view on leaving out the non-async API from the library?

**Comment by bchavez** [comment]
Hi @tmds ,

I haven't fully completed the async API implementation yet. The last thing I need to do for async is properly implement `CancellationToken` mechanism.

Much of the effort has been:
1. Reach API and feature parity with the official Java driver.
2. Extend ReQL expressiveness in C#.
3. Re-work the driver connection architecture to make it thread-safe and usable in apps. The threading architecture in the [.NET driver is currently being back-ported to the Java driver](https://github.com/rethinkdb/rethinkdb/pull/5292).
4. Getting the full battery of unit tests to pass on Windows RethinkDB Server.

I totally understand your motivation for removing non-async API. The future is async in .NET, but I'm hesitant on removing the non-asyinc API from the driver. Here are my thoughts:

* It forces developers to use `async` - I'm hesitant forcing developers to use particular sync/async calling convention. I think giving devs a choice is good.
* Convenience - A lot of value can come from convenience. Sometimes writing a simple C# app / demo to get up and running fast without any hassle is really good. There are times were devs don't want to be bothered with `async`, even if it's not the most efficient.
* A lot of times, proper `async` is easy get wrong - Most commonly, `async void`, `ConfigureAwait`, among others. TBH, having not used it in a while, I got it wrong a few times too... and I think it would only perpetuate these issues.
* Unit tests - Currently, over 1,500+ imported YAML unit test batteries are designed to run synchronously. It would only complicate the import process, impose additional maintenance and complexity when updating unit tests.

I hope you find these reasons acceptable.

**Comment by tmds** [comment]
I think it is good when libraries force developers to adopt modern coding practices.
If a developer still wants blocking calls, he/she can call 'Wait' on the Tasks.

For your unit tests, perhaps you can make the non-async API internal and use the InternalsVisibleToAttribute so the unit tests can still access it?

I will only be using the async methods of this library and I'll frown upon everyone who doesn't ;)

Thanks for the library! Especially the async API!

**Comment by bchavez** [comment]
Hey, no problem. Thanks for giving the driver a try. I really appreciate your input.

After thinking about it a bit more, there could be a possibility of lifting all the non-async API off the core API and move non-async APIs into extension methods. Kind of best of both worlds, but this would be a lot of work right now. My main focus is helping **AtnNn** getting all unit tests to pass on the windows preview. Currently, they all pass on Linux RethinkDB Server, but fail on Windows RethinkDB Server.

Also, after you use the driver for a while (maybe in like a week or so).... I'd appreciate your feedback on the the naming conventions with ReQL... I think I might be getting dinged on points for violating naming conventions when writing ReQL queries. See #18
