### ISSUE TITLE
Microsoft.Extensions.Logging could not be resolved

### ISSUE THREAD

**Issue by fiLLLip** [bchavez/RethinkDb.Driver#3]
Hi, I am trying to include RethinkDb.Driver in a CoreCLR 1.0.0-beta8 build, but an dependency could not be resolved, namely the "Microsoft.Extensions.Logging". See screenshot.
![dep not resolved](https://cloud.githubusercontent.com/assets/1264369/10574040/cb375a88-7653-11e5-9d99-f13cb2d35ee7.png)

**Comment by bchavez** [comment]
Hey there, I think you need the NuGet feed for vnext. AFAIK, `Microsoft.Extensions.Logging` isn't available in the main nuget feed. 

Here's the one we're pulling:
`dnu restore --fallbacksource https://www.myget.org/F/aspnetvnext/api/v2/`

If you visit [https://github.com/aspnet/Logging](https://github.com/aspnet/Logging) , the badges for the main nuget feed are *inaccessible*. Let me know how it goes!

Thanks,
Brian

**Comment by fiLLLip** [comment]
Thanks, man! Worked like a charm :+1:
