### ISSUE TITLE
Support new ‘dotnet’ target framework monikers

### ISSUE THREAD

**Issue by SonicGD** [bchavez/RethinkDb.Driver#32]
We try to use this new monikers - https://github.com/aspnet/Announcements/issues/98, but RethinkDb.Driver targets only old versions - net45, dnxcore50 and dnx451. Can you add dotnet5.4?

**Comment by bchavez** [comment]
Hey there, thanks for reporting the issue. I made some changes to support the new `dotnet` moniker. Could you give [`2.2.8-beta-1`](https://www.nuget.org/packages/RethinkDb.Driver/2.2.8-beta-1) a try?

Let me know if it works for you.

Thanks,
Brian

**Comment by SonicGD** [comment]
Install 2.2.8-beta1, all works good. Thank you. 

But i'm not sure about removing old monikers. As you can see, microsoft packages targets all, old and new, monikers. For example, https://www.nuget.org/packages/EntityFramework.Core/ - targets .NETCore 5.0 and .NETPlatform 5.4. It has 4 folders in lib - dnx451, dotnet5.4, net451, netcore50.

**Comment by bchavez** [comment]
Sure, no problem. I added the old monikers back in [`2.2.8-beta-2`](https://www.nuget.org/packages/RethinkDb.Driver/2.2.8-beta-2). Hopefully Microsoft gets all this straightened out soon. The current state of all these targets stuff is foobar. :8ball:

**Comment by SonicGD** [comment]
Thank you once again.
