### ISSUE TITLE
Does this support streaming of results

### ISSUE THREAD

**Issue by jrote1** [bchavez/RethinkDb.Driver#5]

**Comment by bchavez** [comment]
Hi @jrote1 ,

We're still working on the `Cursor` implementations in both the Java driver and C# driver. It should be finalized soon (sometime this week I hope).

See #4 for some discussion on the topic. I'll leave your issue open until we've finished streaming and the underlying `Cursor` support.

**Comment by bchavez** [comment]
Hey @jrote1 ,

I've completed the `Cursor` implementation; we **should** be able to handle feeds now. Give the driver a try and let us know how it goes.

https://www.nuget.org/packages/RethinkDb.Driver/

Thanks,
Brian

**Comment by bchavez** [comment]
Hi @jrote1 ,

I'm going to close the issue since we now support cursors/streams. If you have any issues, please feel free to file another issue.

Thanks,
Brian
