### ISSUE TITLE
NullReference exception in ReqlExpr

### ISSUE THREAD

**Issue by oliverjanik** [bchavez/RethinkDb.Driver#55]
You've got an override for `==` operator here:

```
    public static ReqlExpr operator ==(ReqlExpr a, ReqlExpr b)
    {
      return (ReqlExpr) a.eq((object) b);
    }
```

This throws when I do a comparison like this: 
```
if (expr == null) ...
```

Got me very confused for a second. Can null be special cased here?

**Comment by bchavez** [comment]
Hey @oliverjanik , I think you need to use `ReferenceEquals` when comparing null with the AST.

Could you provide more context with how you're using and why you're checking `null`?

Thanks,
Brian

**Comment by oliverjanik** [comment]
Yeah that's what I ended up doing, but it confused the hell out of me for a while. Is it intended to be like that?

**Comment by bchavez** [comment]
@oliverjanik Yea, the operator overload for `==` is intended. This allows us to write queries like:

```
.Filter(g => g[nameof(Game.points)].Eq(9))
.Filter(g => g[nameof(Game.points)] == 9) //op overload
```
Fancy! :+1: 

Wiki docs for this are here: https://github.com/bchavez/RethinkDb.Driver/wiki/Extra-C%23-Driver-Features#implicit-conversion-operator-overload

**Comment by oliverjanik** [comment]
`g[nameof(Game.points)]` is never null in these situations, would a null check break anything?

**Comment by bchavez** [comment]
Hey Oliver,

`g[nameof(Game.points)]` isn't `null` per se but I think the field in the JSON document could be `null`. The server would have the necessary information.

Consider what happens with:
```
g => g[nameof(Game.points)] == 9)
```

This check doesn't happen on the client, it happens on the server. `== 9` gets converted into ReQL: `.Eq(9)`. Same would apply for `null`: `== null -> .Eq(null)`

**Comment by oliverjanik** [comment]
Alright then, I'm closing this issue. 

On a sidenote: It feels like Rethink guys reinvented Expression trees in their Java driver.
