### ISSUE TITLE
Can't connect on dotnet core rc2

### ISSUE THREAD

**Issue by SonicGD** [bchavez/RethinkDb.Driver#56]
Hello. We are now moving to rc2 and face problem with RethinkDb.Driver. This code

```cs
_conn = RDB.Connection().Hostname(_host).Port(_port).Connect();
```

throws exception:

```
Attempt by method 'RethinkDb.Driver.Net.SocketWrapper+<ConnectAsync>d__10.MoveNext()' to access method 'System.Net.Sockets.TcpClient.get_Client()' failed
```

As i understand, this commit is caused it:

https://github.com/dotnet/corefx/commit/30abd30421289509cd3bd18a9114501afdc0fb7c

Client property was removed from TCPClient. You are using it here - https://github.com/bchavez/RethinkDb.Driver/blob/master/Source/RethinkDb.Driver/Net/SocketWrapper.cs#L46

**Comment by SonicGD** [comment]
I currently fix this by rewrite SocketWrapper to use Socket directly - https://github.com/SonicGD/RethinkDb.Driver/commit/bb2478271eb1b40c264827c9e48a0d11b54cf7ac

**Comment by jrote1** [comment]
@SonicGD I will look into fixing the issues that have arisen with RC2 tonight, thanks for reporting this and showing the fix you are using

**Comment by bchavez** [comment]
Yoooooo @SonicGD, what's up.

Nuget is loaded up with [`v2.3.2-beta-1`](https://www.nuget.org/packages/RethinkDb.Driver/2.3.2-beta-1) on tap. New driver build should be compatible with `netstandard1.3` **RC2**.

If the new version resolves your issue, hit that close button with vengeance! :+1:

:car: :blue_car: and let the good times roll!! https://www.youtube.com/watch?v=7BDBzgHXf64

**Comment by SonicGD** [comment]
Hey! I will try it today or tomorrow. Thanks!

**Comment by SonicGD** [comment]
Working great =)
