### ISSUE TITLE
"An address incompatible with the requested protocol was used"  on Azure

### ISSUE THREAD

**Issue by ThomasHoest** [bchavez/RethinkDb.Driver#62]
When opening a connection to our db server in an Api App hosted on an App Service on Azure I get the above error. After running directly from source it seems that when opening a socket without `AddressFamily.InterNetwork` made it default to IPv6. Changing this line in SocketWrapper.cs

`this.socket = new Socket(SocketType.Stream, ProtocolType.Tcp );`

to this

`this.socket = new Socket(AddressFamily.InterNetwork, SocketType.Stream, ProtocolType.Tcp );`

and it is wokring as it should.

**Comment by bchavez** [comment]
mange tak, [`v2.3.3`](https://www.nuget.org/packages/RethinkDb.Driver/2.3.3) full framework, [`v2.3.3-beta-1`](https://www.nuget.org/packages/RethinkDb.Driver/2.3.3-beta-1) net core.

:boat: **"Set sail!"** https://www.youtube.com/watch?v=_MqA0a5iw5k

**Comment by ThomasHoest** [comment]
Selv tak :)

And thanks for fixing it so fast. Just changed my whole project to using your driver, great work!
