### ISSUE TITLE
async versions of Dao functions

### ISSUE THREAD

**Issue by Inrego** [bchavez/RethinkDb.Driver#73]
I am quite new to Rethink DB, and therefore also this framework.
I am looking at using the Dao implementation, but I was wondering if we could get async versions of the functions implemented by thiss class?

**Comment by bchavez** [comment]
@Inrego Yo. Thanks! Nice find.

Pushed a new version with `async` DAO methods. Available on Nuget [**`v2.3.7`**](https://www.nuget.org/packages/RethinkDb.Driver/2.3.7)

Aaaaeeeeee ooooooooo... peace :v: 

:walking: :sunglasses: [***"So don't delay... act now supplies are running out..."***](https://www.youtube.com/watch?v=LQj--Kjn0z8)
