### ISSUE TITLE
fromJSONArray not implemented

### ISSUE THREAD

**Issue by fiLLLip** [bchavez/RethinkDb.Driver#8]
~~Trying to fetch an object containing an array throws an exception with the messag `System.Exception: fromJSONArray not implemented`. Further investigation shows that [Profile.cs](https://github.com/bchavez/RethinkDb.Driver/blob/master/Source/RethinkDb.Driver/Model/Profile.cs) throws this error and that in fact is no implemented. I see that the "not yet ready but official" java driver as seen [here](https://github.com/rethinkdb/rethinkdb/blob/josh/java-driver/drivers/java/src/main/java/com/rethinkdb/model/Profile.java) has implemented this (or done something different).~~

~~Is this on the roadmap? I would try to implement this myself, but last time (some time ago now) I tried to build the project it failed. I could try again if your hands are full.~~

**Comment by fiLLLip** [comment]
Heh, I see that this may have been my own fault. I was unaware that I ran against an empty database, and that is why this error was thrown. The function `fromJSONArray` is still not implemented, but the explanation I gave is not entirely accurate.

Here is an updated statement:
Trying to fetch an object from an empty database throws an exception with the message `System.Exception: fromJSONArray not implemented`. Further investigation shows that [Profile.cs](https://github.com/bchavez/RethinkDb.Driver/blob/master/Source/RethinkDb.Driver/Model/Profile.cs) throws this error and that in fact is no implemented. I see that the "not yet ready but official" java driver as seen [here](https://github.com/rethinkdb/rethinkdb/blob/josh/java-driver/drivers/java/src/main/java/com/rethinkdb/model/Profile.java) has implemented this (or done something different).

Is this on the roadmap? I would try to implement this myself, but last time (some time ago now) I tried to build the project it failed. I could try again if your hands are full.

**Comment by bchavez** [comment]
Hm. That's a bit strange. I'm not sure why profile would be activated when querying against an empty DB. Do you have the Debug Traces handy? If not I'll take a look. Be interesting to see how RDB is responding to us.

**Comment by bchavez** [comment]
Also, if you could post the exact ReQL statements that you used to experience the exception, that would be great.

**Comment by bchavez** [comment]
Should be implemented now. Sorry about that.

But I'm still interested in your ReQL statements and the JSON traces if you have them.

Also, you mentioned there was an issue building the driver on your side? Our current CI build status is green. Let me know if you still have trouble, I'd like to make this as frictionless as possible, or update our build WIKI with anything to help users build the driver independently.

**Comment by fiLLLip** [comment]
I don't have the traces available, but my ReQL looks like this:
```
Cursor<Tenant> result = _table.getAll(url).optArg("index", nameof(Tenant.Url)).run<Tenant>(_c.Connection);
```

And Tenant object like this:
```
public class Tenant : BaseModel
    {
        public string Name { get; set; }
        public string[] Url { get; set; }
    }
```
`BaseModel` only contains an `id` of type `string`

**Comment by bchavez** [comment]
Hi @fiLLLip , tracked this down:

The response trace for it:
```
TRACE JSON Received: {"t":18,"e":4100000,"r":["Database `CSharpDriverTests` does not exist."],"n":[],"b":[0,0]}
```

The correct `RethinkDb.Driver.ReqlOpFailedError` exception is now thrown when the DB doesn't exist.

Thanks a bunch for reporting this.

This is fixed in **v0.0.5-alpha5** release. Pushed automatically in a few minutes after CI is done.

**Comment by bchavez** [comment]
Also, wanted to point out **alpha5** has the new opt arg syntax. Give it a try :)

```
Cursor<Tenant> result = _table.getAll(url)[new {index = nameof(Tenant.Url)} )
                              .run<Tenant>(_c.Connection);
```

**Comment by fiLLLip** [comment]
This is great! Will try this tomorrow :+1:

**Comment by fiLLLip** [comment]
```
2015-11-04 08:54:31 [Error] An exception was thrown attempting to execute the error handler.
RethinkDb.Driver.ReqlOpFailedError: Table `test.tenant` does not exist.
   at RethinkDb.Driver.Net.Connection.RunQuery[T](Query query)
   at RethinkDb.Driver.Net.Connection.run[T](ReqlAst term, Object globalOpts)
   at RethinkDb.Driver.Ast.ReqlAst.run[T](Connection conn, Object globalOpts)
```
Works great!
