### ISSUE TITLE
ConnectionPool user and password

### ISSUE THREAD

**Issue by alana1** [bchavez/RethinkDb.Driver#90]
Hello, I am using the RethinkDB c# driver API. I am looking to see if is possible to user user and password in the database connect using the ConnectionPool? I know I can use user and password properties when creating a single connection. Any help would be greatly appreciated.

**Comment by bchavez** [comment]
Hey @alana1 , thanks for your report, we got it done in Issue #87 and PR #88.

New driver release pending soon as Issue #86 and #89 unit tests pass.

:sunny: :crescent_moon: [***"I've been counting down the days and the nights..."***](https://www.youtube.com/watch?v=uMcYRk_o82M)

**Comment by bchavez** [comment]
@alana1 :boom: done.

Just pushed **RethinkDb.Driver** [`v2.3.12`](https://www.nuget.org/packages/RethinkDb.Driver/2.3.12)

Fressssh bits off the press. Should be available in your NuGets when they update their package index. Feel free to re-open the issue if you run into any problems. igotchu.

:guitar: :dancer: [***"Para bailar La Bamba, para bailar La Bamba..."***](https://www.youtube.com/watch?v=Jp6j5HJ-Cok)
