### ISSUE TITLE
Connection.Server error when using proxy

### ISSUE THREAD

**Issue by stefanprodan** [bchavez/RethinkDb.Driver#94]
Hi, 

I using a RethinkDb proxy and when I call `Connection.Server()` I'm getting this:

```
dbug: RethinkDb.Driver[0]
      JSON Recv: Token: 2, JSON: {"t":5,"r":[{"id":"proxy-a711d91a-c391-4161-9a00-51b754a2477f","proxy":true}]}
dbug: LogWatcher.RethinkDbKeepAlive[1001]
      Error converting value "proxy-a711d91a-c391-4161-9a00-51b754a2477f" to type 'System.Guid'. Path 'r[0].id'. Newtonsoft.Json.JsonSerializationException: Error converting value "proxy-a711d91a-c391-4161-9a00-51b754a2477f" to type 'System.Guid'. Path 'r[0].id'. ---> System.ArgumentException: Could not cast or convert from System.String to System.Guid.
   at Newtonsoft.Json.Utilities.ConvertUtils.EnsureTypeAssignable(Object value, Type initialType, Type targetType)
```

Looks like the server guid has a `proxy` prefix.

**Comment by bchavez** [comment]
Yuuup; :scream_cat: and here I thought I was being nice trying to convert the `id` into a `Guid` for you.

I'll get this fixed asap.

:car: :police_car: :rotating_light: [***"Drive it like you stole it..."***](https://www.youtube.com/watch?v=dd00Qh9yZUg)

**Comment by bchavez** [comment]
Hey @stefanprodan , [**`RethinkDb.Driver v2.3.14`**](https://www.nuget.org/packages/RethinkDb.Driver/2.3.14) has been published. Should be available for consumption soon as NuGet updates their package index (within 15 minutes or so).

Thanks again for driving down the bug count in the driver. I really appreciate it.

:violin: :palm_tree: [***"'Cause it's a bittersweet symphony, this life..."***](https://www.youtube.com/watch?v=1lyu1KKwC74)

**Comment by stefanprodan** [comment]
Great, thank you
